apiVersion: apps/v1
kind: Deployment
metadata:
  name: lk8s-challenge-1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: lk8s-challenge-1
  template:
    metadata:
      labels:
        name: lk8s-challenge-1
    spec:
      serviceAccountName: learnk8s-challenge
      containers:
        - name: lk8s-challenge-1
          image: learnk8s/fundamentals:pod
          ports:
            - containerPort: 80
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: lk8s-challenge-1
spec:
  selector:
    name: lk8s-challenge-1
  ports:
    - port: 8080
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lk8s-challenge-1
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /challenge-1
        pathType: Prefix
        backend:
          service:
            name: lk8s-challenge-1
            port:
              number: 8080